export const PERMISSIONS = {
  dashboardView: 'dashboard.view',
  appointmentsView: 'atendimentos.appointments.view',
  appointmentsCreate: 'atendimentos.appointments.create',
  appointmentsUpdate: 'atendimentos.appointments.update',
  appointmentsCancel: 'atendimentos.appointments.cancel',
  appointmentsConfirm: 'atendimentos.appointments.confirm',
  appointmentsCheckin: 'atendimentos.appointments.checkin',
  appointmentsQuickCreate: 'atendimentos.appointments.quick_create',
  consultationsView: 'atendimentos.consultations.view',
  consultationsCreate: 'atendimentos.consultations.create',
  consultationsUpdate: 'atendimentos.consultations.update',
  consultationsDelete: 'atendimentos.consultations.delete',
  consultationsFinalize: 'atendimentos.consultations.finalize',
  consultationsFinalizeAndBill: 'atendimentos.consultations.finalize_and_bill',
  consultationsApproveAnamnesis: 'atendimentos.consultations.approve_anamnesis',
  consultationsAi: 'atendimentos.consultations.ai',
  consultationAttachmentsUpload: 'atendimentos.consultation_attachments.upload',
  consultationAttachmentsDelete: 'atendimentos.consultation_attachments.delete',
  treatmentMapView: 'atendimentos.treatment_map.view',
  prescriptionsView: 'atendimentos.prescriptions.view',
  prescriptionsCreate: 'atendimentos.prescriptions.create',
  prescriptionsPrint: 'atendimentos.prescriptions.print',
  examRequestsView: 'atendimentos.exam_requests.view',
  examRequestsCreate: 'atendimentos.exam_requests.create',
  examRequestsPrint: 'atendimentos.exam_requests.print',
  examResultsCreate: 'atendimentos.exam_results.create',
  examResultsUpload: 'atendimentos.exam_results.upload',
  inpatientView: 'atendimentos.inpatient_records.view',
  inpatientCreate: 'atendimentos.inpatient_records.create',
  inpatientUpdate: 'atendimentos.inpatient_records.update',
  inpatientDischarge: 'atendimentos.inpatient_records.discharge',
  inpatientTransfer: 'atendimentos.inpatient_records.transfer',
  treatmentMapCreate: 'atendimentos.treatment_map.create',
  treatmentMapExecute: 'atendimentos.treatment_map.execute',
  clinicalParametersCreate: 'atendimentos.clinical_parameters.create',
  clientsView: 'clientes.clients.view',
  clientsCreate: 'clientes.clients.create',
  clientsUpdate: 'clientes.clients.update',
  clientsDelete: 'clientes.clients.delete',
  petsView: 'pets.pets.view',
  petsCreate: 'pets.pets.create',
  petsUpdate: 'pets.pets.update',
  petsDelete: 'pets.pets.delete',
  petHistoryView: 'pets.history.view',
  petFilesUpload: 'pets.pet_files.upload',
  salesView: 'financeiro.sales.view',
  salesCreate: 'financeiro.sales.create',
  salesUpdate: 'financeiro.sales.update',
  salesCheckout: 'financeiro.sales.checkout',
  salesCancel: 'financeiro.sales.cancel',
  salesUndoCheckout: 'financeiro.sales.undo_checkout',
  salesReceiptPrint: 'financeiro.sales.receipt.print',
  cashRegistersView: 'financeiro.cash_registers.view',
  cashRegistersCurrent: 'financeiro.cash_registers.current',
  cashRegistersMovements: 'financeiro.cash_registers.movements',
  cashRegistersOpen: 'financeiro.cash_registers.open',
  cashRegistersClose: 'financeiro.cash_registers.close',
  cashRegistersWithdraw: 'financeiro.cash_registers.withdraw',
  cashRegistersManageTerminals: 'financeiro.cash_registers.manage_terminals',
  cashRegistersManagePrinters: 'financeiro.cash_registers.manage_printers',
  cashRegistersPrintOpening: 'financeiro.cash_registers.print_opening',
  cashRegistersPrintClosing: 'financeiro.cash_registers.print_closing',
  paymentsView: 'financeiro.payments.view',
  paymentsCreate: 'financeiro.payments.create',
  paymentsReverse: 'financeiro.payments.reverse',
  commissionsView: 'financeiro.commissions.view',
  commissionsPreview: 'financeiro.commissions.preview',
  commissionsPayout: 'financeiro.commissions.payout',
  commissionsPay: 'financeiro.commissions.pay',
  commissionsUndoPay: 'financeiro.commissions.undo_pay',
  accountsPayableView: 'financeiro.accounts_payable.view',
  accountsPayableCreate: 'financeiro.accounts_payable.create',
  accountsPayableUpdate: 'financeiro.accounts_payable.update',
  accountsPayablePay: 'financeiro.accounts_payable.pay',
  accountsPayableReverse: 'financeiro.accounts_payable.reverse',
  accountsPayableDelete: 'financeiro.accounts_payable.delete',
  accountsReceivableView: 'financeiro.accounts_receivable.view',
  accountsReceivableCreate: 'financeiro.accounts_receivable.create',
  accountsReceivableUpdate: 'financeiro.accounts_receivable.update',
  accountsReceivableReceive: 'financeiro.accounts_receivable.receive',
  accountsReceivableReverse: 'financeiro.accounts_receivable.reverse',
  accountsReceivableDelete: 'financeiro.accounts_receivable.delete',
  fiscalDocumentsView: 'fiscal.documents.view',
  fiscalDocumentsIssue: 'fiscal.documents.issue',
  fiscalDocumentsCancel: 'fiscal.documents.cancel',
  fiscalDocumentsDownload: 'fiscal.documents.download',
  fiscalPendingView: 'fiscal.pending.view',
  fiscalPendingResolve: 'fiscal.pending.resolve',
  fiscalSettingsView: 'fiscal.settings.view',
  fiscalProfilesCreate: 'fiscal.profiles.create',
  fiscalProfilesUpdate: 'fiscal.profiles.update',
  fiscalCertificatesUpload: 'fiscal.certificates.upload',
  fiscalCertificatesUpdatePassword: 'fiscal.certificates.update_password',
  fiscalNfceConfigsUpdate: 'fiscal.nfce_configs.update',
  stockBalancesView: 'estoque.balances.view',
  stockBatchesView: 'estoque.batches.view',
  stockMovementsView: 'estoque.movements.view',
  stockMovementsIn: 'estoque.movements.in',
  stockMovementsOut: 'estoque.movements.out',
  stockMovementsAdjust: 'estoque.movements.adjust',
  reportsView: 'relatorios.reports.view',
  reportsGenerate: 'relatorios.reports.generate',
  reportsDownload: 'relatorios.reports.download',
  reportsHistory: 'relatorios.reports.history',
  usersView: 'cadastros.users.view',
  usersCreate: 'cadastros.users.create',
  usersUpdate: 'cadastros.users.update',
  usersDelete: 'cadastros.users.delete',
  permissionsView: 'cadastros.permissions.view',
  permissionsManage: 'cadastros.permissions.manage',
  appointmentTypesView: 'cadastros.appointment_types.view',
  appointmentTypesCreate: 'cadastros.appointment_types.create',
  appointmentTypesUpdate: 'cadastros.appointment_types.update',
  appointmentTypesDelete: 'cadastros.appointment_types.delete',
  productCategoriesView: 'cadastros.product_categories.view',
  productCategoriesCreate: 'cadastros.product_categories.create',
  productCategoriesUpdate: 'cadastros.product_categories.update',
  productCategoriesDelete: 'cadastros.product_categories.delete',
  suppliersView: 'cadastros.suppliers.view',
  suppliersCreate: 'cadastros.suppliers.create',
  suppliersUpdate: 'cadastros.suppliers.update',
  suppliersDelete: 'cadastros.suppliers.delete',
  boxesView: 'cadastros.boxes.view',
  boxesCreate: 'cadastros.boxes.create',
  boxesUpdate: 'cadastros.boxes.update',
  boxesDelete: 'cadastros.boxes.delete',
  stockLocationsView: 'cadastros.stock_locations.view',
  stockLocationsCreate: 'cadastros.stock_locations.create',
  stockLocationsUpdate: 'cadastros.stock_locations.update',
  stockLocationsDelete: 'cadastros.stock_locations.delete',
  productsView: 'cadastros.products.view',
  productsCreate: 'cadastros.products.create',
  productsUpdate: 'cadastros.products.update',
  productsDelete: 'cadastros.products.delete',
  proceduresView: 'cadastros.procedures.view',
  proceduresCreate: 'cadastros.procedures.create',
  proceduresUpdate: 'cadastros.procedures.update',
  proceduresDelete: 'cadastros.procedures.delete',
  examTypesView: 'cadastros.exam_types.view',
  examTypesCreate: 'cadastros.exam_types.create',
  examTypesUpdate: 'cadastros.exam_types.update',
  examTypesDelete: 'cadastros.exam_types.delete',
  examCategoriesView: 'cadastros.exam_categories.view',
  examCategoriesCreate: 'cadastros.exam_categories.create',
  examCategoriesUpdate: 'cadastros.exam_categories.update',
  examCategoriesDelete: 'cadastros.exam_categories.delete',
  paymentMethodsView: 'cadastros.payment_methods.view',
  paymentMethodsCreate: 'cadastros.payment_methods.create',
  paymentMethodsUpdate: 'cadastros.payment_methods.update',
  paymentMethodsDelete: 'cadastros.payment_methods.delete',
  speciesView: 'cadastros.species.view',
  speciesCreate: 'cadastros.species.create',
  speciesUpdate: 'cadastros.species.update',
  speciesDelete: 'cadastros.species.delete',
  breedsView: 'cadastros.breeds.view',
  breedsCreate: 'cadastros.breeds.create',
  breedsUpdate: 'cadastros.breeds.update',
  breedsDelete: 'cadastros.breeds.delete',
  appointmentStatusesView: 'cadastros.appointment_statuses.view',
  appointmentStatusesCreate: 'cadastros.appointment_statuses.create',
  appointmentStatusesUpdate: 'cadastros.appointment_statuses.update',
  appointmentStatusesDelete: 'cadastros.appointment_statuses.delete',
  clinicSettingsView: 'configuracoes.clinic.view',
  clinicSettingsUpdate: 'configuracoes.clinic.update',
  clinicSettingsImageUpload: 'configuracoes.clinic.image.upload',
  clinicSettingsImageDelete: 'configuracoes.clinic.image.delete',
  availabilityView: 'configuracoes.availability.view',
  availabilityUpdate: 'configuracoes.availability.update',
  supportSystemView: 'suporte.system.view'
} as const

export const ROUTE_PERMISSIONS: Array<{ pattern: RegExp; permissions: string[] }> = [
  { pattern: /^\/$/, permissions: [PERMISSIONS.dashboardView] },
  { pattern: /^\/admin(?:\/|$)/, permissions: [PERMISSIONS.supportSystemView] },
  { pattern: /^\/clinic(?:\/|$)/, permissions: [PERMISSIONS.dashboardView] },
  { pattern: /^\/blank(?:\/|$)/, permissions: [PERMISSIONS.supportSystemView] },
  { pattern: /^\/atendimento\/agendamentos(?:\/|$)/, permissions: [PERMISSIONS.appointmentsView] },
  { pattern: /^\/atendimento\/consultas\/[^/]+\/prescricao\/imprimir(?:\/|$)/, permissions: [PERMISSIONS.prescriptionsPrint] },
  { pattern: /^\/atendimento\/consultas\/[^/]+\/exames\/imprimir(?:\/|$)/, permissions: [PERMISSIONS.examRequestsPrint] },
  { pattern: /^\/atendimento\/consultas(?:\/|$)/, permissions: [PERMISSIONS.consultationsView] },
  { pattern: /^\/consultas\/novo-atendimento(?:\/|$)/, permissions: [PERMISSIONS.consultationsCreate] },
  { pattern: /^\/atendimento\/internacao(?:\/|$)/, permissions: [PERMISSIONS.inpatientView] },
  { pattern: /^\/clientes(?:\/|$)/, permissions: [PERMISSIONS.clientsView] },
  { pattern: /^\/pets(?:\/|$)/, permissions: [PERMISSIONS.petsView] },
  { pattern: /^\/financeiro\/vendas\/nova(?:\/|$)/, permissions: [PERMISSIONS.salesCreate] },
  { pattern: /^\/financeiro\/vendas(?:\/|$)/, permissions: [PERMISSIONS.salesView] },
  { pattern: /^\/financeiro\/caixa(?:\/|$)/, permissions: [PERMISSIONS.cashRegistersView] },
  { pattern: /^\/financeiro\/comissoes(?:\/|$)/, permissions: [PERMISSIONS.commissionsView] },
  { pattern: /^\/financeiro\/contas-a-pagar(?:\/|$)/, permissions: [PERMISSIONS.accountsPayableView] },
  { pattern: /^\/financeiro\/contas-a-receber(?:\/|$)/, permissions: [PERMISSIONS.accountsReceivableView] },
  { pattern: /^\/fiscal\/documentos(?:\/|$)/, permissions: [PERMISSIONS.fiscalDocumentsView] },
  { pattern: /^\/fiscal\/pendencias(?:\/|$)/, permissions: [PERMISSIONS.fiscalPendingView] },
  { pattern: /^\/fiscal\/configuracoes(?:\/|$)/, permissions: [PERMISSIONS.fiscalSettingsView] },
  { pattern: /^\/estoque\/saldos(?:\/|$)/, permissions: [PERMISSIONS.stockBalancesView] },
  { pattern: /^\/estoque\/movimentacoes(?:\/|$)/, permissions: [PERMISSIONS.stockMovementsView] },
  { pattern: /^\/relatorios(?:\/|$)/, permissions: [PERMISSIONS.reportsView] },
  { pattern: /^\/usuarios(?:\/|$)/, permissions: [PERMISSIONS.usersView] },
  { pattern: /^\/cadastros\/permissoes(?:\/|$)/, permissions: [PERMISSIONS.permissionsView] },
  { pattern: /^\/cadastros\/tipos-agendamento(?:\/|$)/, permissions: [PERMISSIONS.appointmentTypesView] },
  { pattern: /^\/cadastros\/categorias-produto(?:\/|$)/, permissions: [PERMISSIONS.productCategoriesView] },
  { pattern: /^\/cadastros\/fornecedores(?:\/|$)/, permissions: [PERMISSIONS.suppliersView] },
  { pattern: /^\/cadastros\/boxes(?:\/|$)/, permissions: [PERMISSIONS.boxesView] },
  { pattern: /^\/cadastros\/locais-estoque(?:\/|$)/, permissions: [PERMISSIONS.stockLocationsView] },
  { pattern: /^\/cadastros\/produtos(?:\/|$)/, permissions: [PERMISSIONS.productsView] },
  { pattern: /^\/cadastros\/procedimentos(?:\/|$)/, permissions: [PERMISSIONS.proceduresView] },
  { pattern: /^\/cadastros\/exames(?:\/|$)/, permissions: [PERMISSIONS.examTypesView] },
  { pattern: /^\/cadastros\/formas-pagamento(?:\/|$)/, permissions: [PERMISSIONS.paymentMethodsView] },
  { pattern: /^\/tabelas\/especies(?:\/|$)/, permissions: [PERMISSIONS.speciesView] },
  { pattern: /^\/tabelas\/racas(?:\/|$)/, permissions: [PERMISSIONS.breedsView] },
  { pattern: /^\/tabelas\/status(?:\/|$)/, permissions: [PERMISSIONS.appointmentStatusesView] },
  { pattern: /^\/configuracoes\/clinica(?:\/|$)/, permissions: [PERMISSIONS.clinicSettingsView] },
  { pattern: /^\/configuracoes\/escalas-disponibilidade(?:\/|$)/, permissions: [PERMISSIONS.availabilityView] }
]

export const findRoutePermissions = (path: string) => {
  return ROUTE_PERMISSIONS.find((item) => item.pattern.test(path))?.permissions || []
}
